services:
  - type: web
    name: smart-recipes-api
    env: node
    plan: free
    buildCommand: npm install && npm run build:simple
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: smart-recipes-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true

databases:
  - name: smart-recipes-db
    databaseName: smart_recipes
    user: smart_recipes_user
    plan: free 