name: Backend Deployment

on:
  push:
    branches: [main, openai]
    paths:
      - 'server/**'
      - 'database/**'
      - '.github/workflows/backend-deploy.yml'
  pull_request:
    branches: [main]
    paths:
      - 'server/**'
      - 'database/**'

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: smart_recipes_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup test database
        run: |
          PGPASSWORD=test_password psql -h localhost -U test_user -d smart_recipes_test -f ../database/schema.sql
        env:
          PGPASSWORD: test_password

      - name: Run type checking
        run: npx tsc --noEmit
        continue-on-error: true

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test -- --coverage --forceExit
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/smart_recipes_test
          JWT_SECRET: test-jwt-secret-for-ci
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true

      - name: Test production build
        run: npm run start:tsx &
        env:
          NODE_ENV: production
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/smart_recipes_test
          JWT_SECRET: test-jwt-secret-for-ci
          PORT: 3001

      - name: Health check
        run: |
          sleep 10
          curl -f http://localhost:3001/api/health || exit 1
          curl -f http://localhost:3001/api/db-test || exit 1

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage
          path: server/coverage
          retention-days: 7

  deploy-railway:
    name: Deploy to Railway
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/railway-deploy@v3
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          service: smart-recipes-api
          environment: production

  deploy-render:
    name: Deploy to Render (Backup)
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && failure()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level moderate
        continue-on-error: true

      - name: Run security scan
        uses: securecodewarrior/github-action-add-sarif@v1
        if: always()
        with:
          sarif-file: 'security-scan-results.sarif' 